### ISSUE TITLE
[Android Bootcamp] Project 0: Todo - Ready for Review

### ISSUE THREAD

**Issue by marcochin** [marcochin/Sugoi-To-Do-List#1]
Hi CodePath, my app is complete and ready for review. Thanks! /cc @codepathreview @codepath

**Comment by nesquena** [comment]
Marco,

Based on your LinkedIn it is unclear if you meet the [selection criteria for the course](http://courses.codepath.com/snippets/intro_to_android/selection_criteria). Can you review that and let me know if you can confirm that you meet the requirements? As far as I can tell, you've never worked professionally as an engineer yet since you graduated quite recently?

**Comment by marcochin** [comment]
Hey Nathan,
Yes, that is true. I have never worked professionally as an engineer, but I
feel i have the technical skills to go through this camp successfully and
was wondering if you can maybe make an exception as it would help me
tremendously.

**Comment by nesquena** [comment]
Thanks for the notes Marco. Happy for you have to applied and that you submitted the assignment here. Appreciate the UI work and optionals you've completed. Note that the course is focused on people with a particular number of years of professional experience because this allows for the course to move faster and for groups of people to work together significantly smoother.  Any program that combines people of significantly different professional experience levels tends to be much less effective. 

That said, I do appreciate the work you've submitted here and I will add you onto the waiting list for the course. Each round, we select a few people that don't meet the full course requirements and allow them in from the waiting list based on the quality of the extensions to their pre-work submissions. I'll follow up again in mid-July.

**Comment by marcochin** [comment]
Thanks, appreciate it. Should I close the issue or leave it open?

**Comment by nesquena** [comment]
Feel free to close or leave open, the submission has already been tracked by our systems.
